# 
env:
  - CN_SENCHA_EXT_VERSION="6.2.0" CN_SENCHA_CMD_VERSION="6.2.2.36" 
install:
  - gem install jsduck
before_script:
  
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  
  - "wget http://cdn.sencha.com/ext/gpl/ext-$CN_SENCHA_EXT_VERSION-gpl.zip"
  - "unzip -q ext-$CN_SENCHA_EXT_VERSION-gpl.zip"
  - "ln -sv `pwd`/ext-$CN_SENCHA_EXT_VERSION $TRAVIS_BUILD_DIR/../ext"
  
  - "wget http://cdn.sencha.com/cmd/$CN_SENCHA_CMD_VERSION/no-jre/SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "unzip -q SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh.zip"
  - "chmod +x SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh"
  - "./SenchaCmd-$CN_SENCHA_CMD_VERSION-linux-amd64.sh -q"
  
  - "export PATH=~/bin/Sencha/Cmd/$CN_SENCHA_CMD_VERSION/:$PATH"
  

  - "mkdir /tmp/conjoon"
  - "sencha -sdk $TRAVIS_BUILD_DIR/../ext generate workspace /tmp/conjoon"
  - "cp $TRAVIS_BUILD_DIR/* /tmp/conjoon/packages/local/theme-cn_default -R"

  - "cd $TRAVIS_BUILD_DIR && sencha package build"
  
  - "cd $TRAVIS_BUILD_DIR"